[project]
name = "marpledata"
version = "2.2.1"
description = "Marple SDK for Python"
authors = [
  "Matthias Baert <support@marpledata.com>",
  "Jan Scheers <jan@marpledata.com>",
]
readme = "README.md"
license = "Apache-2.0"
homepage = "https://www.marpledata.com/"
documentation = "https://docs.marpledata.com/docs"
requires-python = ">=3.13"
dependencies = [
  "numpy>=2.3.5",
  "pandas>=2.3.3",
  "pyarrow>=22.0.0",
  "requests>=2.32.5",
]
